"""Regenerate ``docs/data.js`` from ``results/``.

    python scripts/build_frontend.py

The page is never hand-edited with numbers pasted into it. Everything it draws
comes from this file, which reads what ``scripts/make_results.py`` wrote and
emits one JavaScript object literal.

Why a ``.js`` file rather than ``.json``: the page must open by double-clicking
it, and a browser reading a ``file://`` page refuses to ``fetch()`` a local
JSON file under its CORS rules. A ``<script src="data.js">`` tag is not subject
to that, so the data arrives as a global. This is the single constraint that
decides the architecture of the whole front end.

Rounding is deliberate. Every float is written to the precision that matters
for a chart - four decimals on basis points, two on prices - because the
alternative is shipping seventeen significant figures of Monte Carlo noise and
a data file several times larger than it needs to be.
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.utils.config import AppConfig  # noqa: E402

RESULTS = ROOT / "results"
DOCS = ROOT / "docs"


def rnd(x: Any, nd: int = 4) -> Any:
    """Round for shipping. ``NaN`` and infinities become ``null``, because
    ``JSON.parse`` has no way to represent them and a raw ``NaN`` in a
    JavaScript literal is a silent parse error in some engines."""
    if isinstance(x, (int,)) and not isinstance(x, bool):
        return x
    if isinstance(x, float):
        if not math.isfinite(x):
            return None
        # Decimal rounding would send a risk aversion of 1e-7 to zero, and the
        # page would then label every Almgren-Chriss variant "lambda = 0".
        # Anything smaller than the rounding step keeps four significant
        # figures instead.
        if x != 0.0 and abs(x) < 10.0 ** (-nd):
            return float(f"{x:.4g}")
        return round(x, nd)
    if isinstance(x, dict):
        return {k: rnd(v, nd) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [rnd(v, nd) for v in x]
    return x


def main() -> int:
    summary_path = RESULTS / "summary.json"
    if not summary_path.exists():
        print("results/summary.json is missing - run scripts/make_results.py first",
              file=sys.stderr)
        return 1
    cfg = AppConfig.load()
    S = json.loads(summary_path.read_text(encoding="utf-8"))
    tape = json.loads((RESULTS / "tape.json").read_text(encoding="utf-8"))

    data: Dict[str, Any] = {
        "meta": {
            "generated": S["generated"],
            "as_of": S["as_of"],
            "source": S["source"],
            "ticker": S["ticker"],
            "repo": "https://github.com/codeebytee/08-lob-optimal-execution",
        },
        "config": rnd(S["config"], 8),
        "names": {t: rnd(v, 8) for t, v in S["names"].items()},
        "impact": {
            "gamma": S["impact"]["gamma"],
            "eta": S["impact"]["eta"],
            "epsilon": S["impact"]["epsilon"],
            "exponent": rnd(S["impact"]["exponent"], 3),
            "exponent_r2": rnd(S["impact"]["exponent_r2"], 3),
            "linear_r2": rnd(S["impact"]["linear_r2"], 3),
            "rows": rnd(S["impact"]["rows"], 6),
        },
        "summary": rnd(S["summary"], 4),
        "paired": rnd(S["paired"], 4),
        "frontier_model": rnd(S["frontier_model"], 4),
        "frontier_sim": rnd(S["frontier_sim"], 4),
        "cross_section": rnd(S["cross_section"], 4),
        "histograms": S["histograms"],
        "tape": tape,
    }

    DOCS.mkdir(exist_ok=True)
    out = DOCS / "data.js"
    payload = json.dumps(data, separators=(",", ":"), allow_nan=False)
    out.write_text(
        "/* Generated by scripts/build_frontend.py - do not edit by hand.\n"
        f"   Source: results/summary.json, results/tape.json\n"
        f"   Market data as of {S['as_of']} ({S['source']}).\n"
        f"   Regenerate with: python scripts/make_results.py && "
        "python scripts/build_frontend.py */\n"
        "window.DATA = " + payload + ";\n",
        encoding="utf-8")

    size_kb = out.stat().st_size / 1024
    print(f"wrote {out.relative_to(ROOT)}  ({size_kb:.0f} KB)")
    print(f"  {len(data['summary'])} grid rows, {len(data['histograms'])} histograms, "
          f"{len(tape['frames'])} animation frames, {len(data['names'])} names")
    total = sum(p.stat().st_size for p in DOCS.rglob("*") if p.is_file())
    print(f"  docs/ total {total / 1024 / 1024:.2f} MB (budget 8 MB)")
    if total > 8 * 1024 * 1024:
        print("  OVER BUDGET", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
